# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build_and_test:
    working_directory: ~/prometheus-cardinality-exporter
    machine: true
    steps:
      - checkout
      - run:
          name: Build Alpine Docker Image
          command: docker build -f Dockerfile-builder . --rm=false -t thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"
      - run:
          name: Build distroless Docker Image
          command: docker build -f Dockerfile-builder_distroless . --rm=false -t thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"_distroless
  build_and_release:
    working_directory: ~/prometheus-cardinality-exporter
    machine: true
    steps:
      - checkout
      - run:
          name: Build Alpine Docker Image
          command: docker build -f Dockerfile-builder . --rm=false -t thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"
      - run:
          name: Build distroless Docker Image
          command: docker build -f Dockerfile-builder_distroless . --rm=false -t thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"_distroless
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"
            docker push thoughtmachine/prometheus-cardinality-exporter:"$CIRCLE_SHA1"_distroless
workflows:
  version: 2
  build-master:
    jobs:
      - build_and_release:
          context: conntest-dockerhub-release
          filters:
            branches:
              only: master
  test-buildable:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
