---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cardinality-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - endpoints
    verbs:
      - list
