---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-cardinality-exporter-secret
  namespace: example-namespace
stringData:
  prometheus-api-auth-values.yaml: |
    example-namespace_example-prometheus-instance_example-sharded-instance: "Basic YWRtaW46cGFzc3dvcmQ=" # set Authorization header for specific sharded instance
    example-namespace_example-prometheus-instance: "Bearer 123456789" # set Authorization header for all sharded instances that have the Prometheus instance name "example-prometheus-instance" in namespace "example-namespace"
    example-namespace: "Basic 123456789" # set Authorization header for all instances in namespace "example-namespace"
