---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-cardinality-exporter-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    app: prometheus-cardinality-exporter
    project: cardinality-exporter
    team: cloud
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app: prometheus-cardinality-exporter
    project: cardinality-exporter
